#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build lib script ..."
./node_modules/.bin/lsc -cbp --no-header src/lib.ls > dist/lib.js
./node_modules/.bin/uglifyjs dist/lib.js -m -c > dist/lib.min.js
echo "build pug files to html files ..."
echo "index.pug ..."
./node_modules/.bin/srcbuild-pug src/index.pug > dist/index.html
echo "copy dist into static folder..."
rm -rf web/static/assets/lib/block/main/
mkdir -p web/static/assets/lib/block/main/
cp -R dist/* web/static/assets/lib/block/main/
echo "done."
